// USER/AUTH ACTIONS
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_ERROR = "USER_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
export const LOAD_USER_FROM_STORAGE = "LOAD_USER_FROM_STORAGE";
export const CLEAR_ERROR = "CLEAR_ERROR";

// CATEGORY ACTIONS
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_LOADED = "CATEGORY_LOADED";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

// PRODUCT ACTIONS
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

// PAYMENT ACTIONS
export const PAYMENT_LOADING = "PAYMENT_LOADING";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

// ADD TO CART ACTIONS
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

// REMOVE TO CART ACTIONS
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
